#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 31 03:19:08 2018

@author: mukul
"""

reader = open("file.csv", "r")
lines = reader.read().split("\n")
reader.close()
 
writer = open("file.csv", "w")
for line in set(lines):
    writer.write(line + "\n")
writer.close()